apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust2165902298089357120
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider1flux+cluster1/context/2165902298089357120
  prune: true
  sourceRef:
    kind: GitRepository
    name: "2165902298089357120"
  targetNamespace: default
status: {}
